### ISSUE TITLE
Semantic Analysis TODO

### ISSUE THREAD

**Issue by akrs** [akrs/YACBL#14]
See slack for list of operators and types.
- [ ] Operator can verify the type of the operands
- [ ] Function can verify the return values
- [ ] Return statement can verify that it is inside a function
- [ ] Blocks can maintain lists of variables within them
- [ ] Programs can maintain lists of their variables
